import type { NextPage } from 'next';
import Head from 'next/head';
import BigMapLayout from '../layouts/BigMapLayout';
import Header from '../component/Header';
import Footer from '../component/Footer';

const Home: NextPage = () => {
  return (
    <div className='bg-secondary m-0 p-0'>
      <Head>
        <title>Campus in de buurt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header selected={false} />
        <BigMapLayout />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
